theme: osuny
_merge: deep
outputs:
  page:
  - html
  section:
  - html
  - rss
params:
  debug:
    productionUrl: https://www.la-criee.org
  plausible: la-criee.org
  menu:
    primary:
      level_2:
        title:
          active: true
  breadcrumb:
    position: hero-start
  search:
    active: true
    positions:
      - footer
      - primary
  i18n:
    positions:
      - primary
      # - upper-menu
      # - footer
  summary:
    position: content
  home:
    head:
      title: site
  events:
    date_format: "02 January 2006"
    index:
      options:
        categories: true
        dates: false
      # layout: list
    single:
    #   calendar_links: true
    #   meta_in_sidebar: true
      navigation: 
        active: false
  persons:
    index:
      layout: grid
    single:
      backlinks: true
  posts:
    index:
      layout: grid
  organizations:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
    share_links:
      facebook: true
      twitter: false
      linkedin: true
      email: false
      telegram: false
      whatsapp: false
  projects:
    index:
      options:
        categories: true
        summary: true
        year: true
  image_sizes:
    blocks:
      gallery:
        grid:
          desktop:  555
    sections:
      events:
        layouts:
          large:
            desktop:  864
          list:
            desktop:  245
      persons:
        layouts:
          grid:
            mobile:   100
            tablet:   277
            desktop:  400