theme: osuny
paginate: 36
enableRobotsTXT: true
removePathAccents: true
params:
  menu:
    dropdown:
      linkToLevel1: true
  breadcrumb:
    position: hero-start
  search:
    active: true
    position: footer
    appearance: both
  summary:
    position: content
  events:
    index:
      show_categories: true
  persons:
    index:
      layout: grid
    single:
      backlinks: true
  posts:
    index:
      layout: grid
  organizations:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
    share_links:
      facebook: true
      twitter: false
      linkedin: true
      email: false
      telegram: false
      whatsapp: false
  image_sizes:
    blocks:
      persons:
        mobile:   68
        tablet:   277
        desktop:  400
  projects:
    index:
      show_year: true
  image_sizes:
    blocks:
      gallery:
        grid:
          desktop:  555
      persons:
        desktop:  400
    sections:
      events:
        item:
          desktop:  864