theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  menu:
    dropdown:
      linkToLevel1: true
  breadcrumb:
    position: hero-start
  search:
    active: true
    position: footer
    appearance: both
  summary:
    position: content
  events:
    index:
      show_categories: true
  persons:
    index:
      layout: grid
    single:
      backlinks: true
  posts:
    index:
      layout: grid
  organizations:
    single:
      backlinks: true
